- name: Create necessary directories
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ cw_alarms_build_dir }}"
    - "{{ cw_alarms_template_dir }}"

- name: Template alarms
  template:
    src: cloudwatch.json.j2
    dest: "{{ cw_alarms_template_dir }}/{{ cw_alarms_template_name }}"


- shell: "cat {{ cw_alarms_template_dir }}/{{ cw_alarms_template_name }}"


- name: Deploy alarms
  cloudformation:
    template: "{{ cw_alarms_template_dir }}/{{ cw_alarms_template_name }}"
    region: "{{ cw_alarms_region }}"
    stack_name: "{{ cw_alarms_stack_name }}"
    state: "{{ cw_alarms_stack_state }}"
    security_token: "{{ ansible_security_token | default(omit, true) }}"
    region: "{{ cw_alarms_stack_region }}"
